export { Navbar } from "./Navbar";
export { Hero } from "./Hero";
export { About } from "./About";
export { Skills } from "./Skills";
export { Experience } from "./Experience";
export { Project } from "./Project";
export { Education } from "./Education";
export { Contact } from "./Contact";
export { Footer } from "./Footer";
